---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprormq
spec:
  selector:
    matchLabels:
      app: vprormq
  template:
    metadata:
      labels:
        app: vprormq
    spec:
      containers:
      - name: vprormq
        image: rabbitmq
        ports:
          - name: vpromq-port
            containerPort: 15672
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: "guest"
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: rmq-pass
---
apiVersion: v1
kind: Service
metadata:
  name: vprormq
spec:
  selector:
    app: vprormq
  ports:
  - port: 15672
    targetPort: 15672

